# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3U40qn-oh8BqQ90coWK48ZKmMhfdDIQ
"""

# 这是一个 streamlit 脚本示例
import streamlit as st

st.title("我的第一个Streamlit应用")
st.write("Hello, Streamlit!")